name: CI/CD for FastAPI App

on:
  push:
    branches:
      - main  # Change if using a different branch

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"  # Use your Python version

      - name: Remove Cached Dependencies
        run: rm -rf ~/.cache/pip

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt
          pip install --upgrade fastapi starlette httpx



      - name: Run Tests
        run: |
          pytest --cov=app tests/ -p no:warnings --cov-report=xml

  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/vinaykontham:${{github.sha}} .
          docker tag ${{ secrets.DOCKER_USERNAME }}/vinaykontham:${{github.sha}} ${{ secrets.DOCKER_USERNAME }}/vinaykontham:latest

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/vinaykontham:latest

  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "latest"

      - name: Configure Kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > $HOME/.kube/config
          chmod 600 $HOME/.kube/config
          export KUBECONFIG=$HOME/.kube/config
          kubectl config view
          kubectl config use-context gke_hip-caster-451209-f0_us-central1_python-cluster

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/ -n pasteclone
